services:
  pagerank:
    build:
      context: .
      target: base
    image: akrishnaams/access-bit-pagerank-gapbs:latest
    container_name: pagerank
    network_mode: host
    # pid: host
    privileged: true
    environment:
      - GRAPH_DIR=/dataset
      - OUTPUT_DIR=/dataset
      - OMP_NUM_THREADS=${OMP_NUM_THREADS:-0}
    volumes:
      - /mnt/sdb/arun/workloads/gapbs/:/dataset
    command: /bin/bash
    stdin_open: true
    tty: true
    cpuset: 0-3
